### ISSUE TITLE
Assignment 0 Link Issue

### ISSUE THREAD

**Issue by LWeeks97** [tamucc-comp-bio-2022/classroom_repo#1]
The link to Assignment 0 under the first README file before you go into any of the folders in the repository links you to Assignment 0 from 2020 (https://github.com/tamucc-comp-bio-2022/classroom_repo/blob/master/assignments/assignment_0.md).

The link to Assignment 0 that is within the Week 0 Intro we went through on the first day seems to be correct (or at least recently updated).

**Comment by cbird808** [comment]
Thank you!  Fixed!
