### ISSUE TITLE
Mind Expander 01.02 Link Issue

### ISSUE THREAD

**Issue by LWeeks97** [tamucc-comp-bio-2022/classroom_repo#2]
The link to Mind Expander 01.02 inside the assignment 1 page links to the grad students project idea form (https://forms.office.com/Pages/ResponsePage.aspx?id=8frLNKZngUepylFOslULZlFZdbyVx8RLiPt1GobhHnlUOUo2UVRUMVgwTUlQMlpUQzUzOTIzME9LNi4u).

**Comment by cbird808** [comment]
Thank you! Fixed!
