### ISSUE TITLE
Cloning repositories

### ISSUE THREAD

**Issue by roberttungate12** [tamucc-comp-bio-2022/classroom_repo#4]
"Please try to at least click the link and let me know if you run into any problems getting the assignment or cloning the repo"

I don't know if it's necessary to mention in the instructions, but mentioning the SSH keys might be useful to help guide students to cloning repositories.

I've had to help a few that forgot they set up an SSH key for their laptop and they have to use the SSH link to clone repositories now. The same things would help with assignment 3.

**Comment by cbird808** [comment]
agreed!
